version: 2

updates:
  # Update npm packages
  - package-ecosystem: npm
    directory: /
    open-pull-requests-limit: 10

    # Group packages into shared PR
    groups:
      build:
        patterns:
          - '@babel/*'
          - 'autoprefixer'
          - 'babel-plugin-module-resolver'
          - 'babel-loader'
          - 'babel-plugin-transform-import-meta'
          - 'cssnano'
          - 'cssnano-*'
          - 'tsx'
          - 'webpack'
          - 'webpack-*'
          - 'terser-webpack-plugin'
          - 'clean-webpack-plugin'
          - 'copy-webpack-plugin'
          - 'source-map-loader'
          - 'sass'
          - 'sass-*'
          - 'postcss-*'

      lint:
        patterns:
          - 'prettier'
          - 'stylelint'
          - 'stylelint-*'
          - 'neostandard'
          - 'eslint'

      logging:
        patterns:
          - '*-pino'
          - '*-pino-format'
          - 'pino'
          - 'pino-*'
          - '@elastic/ecs-pino-format'
          - 'aws-embedded-metrics'

      tools:
        patterns:
          - 'husky'
          - 'cross-env'
          - 'nodemon'
          - 'npm-run-all'
          - 'semver'

      testing:
        patterns:
          - 'vitest'
          - 'vitest-*'
          - '@vitest/*'
          - '@testing-library/*'
          - 'cheerio'
          - 'jsdom'

      hapi:
        patterns:
          - '@hapi/*'
          - 'hapi-*'
          - '@defra/hapi-*'

      config:
        patterns:
          - 'convict'
          - 'convict-format-with-validator'
          - 'dotenv'

      code:
        patterns:
          - 'lodash'
          - 'blankie'
          - 'date-fns'
          - 'ioredis'
          - 'node-fetch'
          - 'nunjucks'
          - 'undici'

    ignore:
      - dependency-name: 'eslint-*'
      - dependency-name: 'eslint'

    # Schedule run every Monday, local time
    schedule:
      interval: weekly
      time: '10:30'
      timezone: 'Europe/London'

    versioning-strategy: increase

    allow:
      # Include direct package.json updates
      - dependency-type: direct

  # Update GitHub Actions
  - package-ecosystem: github-actions
    directory: /

    # Schedule run every Monday, local time
    schedule:
      interval: weekly
      time: '10:30'
      timezone: 'Europe/London'
